### ISSUE TITLE
Fix several hypen-use-as-minus-sign issues

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop-legacy-archive/mate-dialogs#15]
The matedialog man page still uses hyphens as minus sign at several places. All occurrences of "-" should be replaced by "-".

This issue popped up from Linitan [1].

Thanks+Greets,
Mike

[1] http://lintian.debian.org/tags/hyphen-used-as-minus-sign.html

**Comment by sunweaver** [comment]
Find a patch here:
http://anonscm.debian.org/gitweb/?p=pkg-mate/mate-dialogs.git;a=blob;f=debian/patches/1001_fix-use-hyphen-as-minus-sign.patch;h=fd9b1afad67775cdb457f940683a4f0d4896d4a5;hb=a20fae0602a3cbe6c184a15f6f639628976b819c

**Comment by sunweaver** [comment]
... all occurences of "-" should be replaced by "[backslash]-"... :-)

**Comment by infirit** [comment]
@sunweaver I put your patch in a pull request and @stefano-k now merged them. If you have more patches you could open a pull request and @stefano-k can merge them directly :).

@stefano-k this one can be closed now that the 2 pulls have been merged.
