### ISSUE TITLE
Add dektop file for Color Selection

### ISSUE THREAD

**Issue by GreenLunar** [mate-desktop-legacy-archive/mate-dialogs#18]
I do not use [gcolor2 - GTK+2 Color Selector](http://gcolor2.sourceforge.net/), because `matedialog --color-selection` is enough for me and, also, gcolor2 is not, yet, available in GTK+3.

**Comment by flexiondotorg** [comment]
@monsta @infirit I've not looked at how it is implemented but this already exists in MATE 1.10, correct?

**Comment by monsta** [comment]
Of course:
https://github.com/mate-desktop/mate-desktop/blob/master/tools/mate-color-select.desktop.in.in

Close this one - mate-dialogs is deprecated since 1.10 :smile:

**Comment by GreenLunar** [comment]
I still think this small addition is worth to add.

Open this ticket if you like to.

**Comment by monsta** [comment]
Worth to add where? This project is dropped in 1.10 :smile:

**Comment by GreenLunar** [comment]
Here, in case someone would fork it.

**Comment by monsta** [comment]
Why? There's `zenity` for the same purposes.

**Comment by GreenLunar** [comment]
You are correct.

I will not bother send a report to GNOME bug tracker (I have no account).  GitHub repository is locked for issues https://github.com/GNOME/zenity

If anyone may, please send a link to this thread to GNOME bug tracker.
