### ISSUE TITLE
Save as... dialog when switching folders

### ISSUE THREAD

**Issue by MartinThoma** [mate-desktop-legacy-archive/mate-dialogs#19]
When I'm in the following situation and I want to save the file in the current folder by clicking on "save", it only opens the selected folder "Statistik":

![Imgur](http://i.imgur.com/EshHtmw.png)

It should be possible to click at the white space below the folder "Wahrscheinlichkeitstheorie" to "deselect" the folder "Statistik".

**Comment by monsta** [comment]
1. This is GTK+ dialog. It's not created by `mate-dialogs`. Please file a bug against GTK+ in your distro.
2. There's no use reporting bugs against discontinued apps anyway (`mate-dialogs` has been dropped in 1.10, users should switch to `zenity` which does the same thing).

**Comment by MartinThoma** [comment]
I'm sorry, I didn't know where to report this issue. Could you please tell me the website where I can report it?

I have Ubuntu 15.10 MATE.

**Comment by monsta** [comment]
https://launchpad.net/ubuntu/+source/gtk+2.0/+bugs
https://launchpad.net/ubuntu/+source/gtk+3.0/+bugs

depending on GTK+ version used
