### ISSUE TITLE
replace the current COPYING file for the original one

### ISSUE THREAD

**Issue by ghost** [mate-desktop-legacy-archive/mate-dialogs#2]
People,

A license file is a legal document, therefore it shouldn't be patched in any way; My suggestiong is that we remove the current COPYING file and replace it by the original (I know it's exactly the same thing and editing it), but from a legal point of view, I'm not sure if editing legal documents is acceptable.

The original file can be obtained in: http://www.gnu.org/licenses/gpl-2.0.txt

Stephano or Perberos, or anyone else... Can you guys remove and add the right file so that we keep record that the file was replaced totally and not hacked ?

Thanks.

**Comment by mahiuchun** [comment]
Wait a second, your README says "This software is licensed under the LGPL."
