### ISSUE TITLE
gdialog script conflicts with gdialog in package zenity of gnome3

### ISSUE THREAD

**Issue by rezso** [mate-desktop-legacy-archive/mate-dialogs#5]
E: /home/attila/Nyilvános/ubk/2.2/MATE/mate-dialogs_1.5.1-1.3_i386.ubk.uhu: trying to overwrite '/usr/bin/gdialog', which is also in package zenity 0:3.4.0-1.1

**Comment by stefano-k** [comment]
This is known. gdialog is provided to enable zenity support without have zenity. You need to split it into another package, or delete it, at distro packaging level.
