### ISSUE TITLE
[RPMLint] no-manual-page-for-binary

### ISSUE THREAD

**Issue by posophe** [mate-desktop-legacy-archive/mate-dialogs#6]
no-manual-page-for-binary gdialog
Each executable in standard binary directories should have a man page.

**Comment by raveit65** [comment]
You should remove gdialogs from your rpm. Same like zenity do in most distros.
I will do that for fedora too.
Currently we are thinking about to remove gdialog complete from mate-dialogs.

**Comment by posophe** [comment]
Already done :)

**Comment by posophe** [comment]
I have to close it I suppose

**Comment by raveit65** [comment]
done!
https://github.com/mate-desktop/mate-dialogs/pull/8
